version: "3.1"

services:
  mongo:
    image: mongo:3.6.18-xenial
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      webnet:
        aliases:
          - mongo

  app:
    build: .
    image: kuva:dev
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    networks:
      - webnet
    depends_on:
      - mongo
    command: sh -c "rm -f /tmp/server.pid && bundle && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"

networks:
  webnet:

volumes:
  dbdata:
  bundle:
